# Generated by Django 6.0 on 2025-12-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MangaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('votes', models.IntegerField()),
                ('ranked', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('members', models.IntegerField()),
                ('favorites', models.IntegerField()),
                ('volumes', models.IntegerField()),
                ('chapters', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('published', models.CharField(max_length=50)),
                ('serialization', models.CharField(max_length=255)),
                ('authors', models.ManyToManyField(to='api.author')),
                ('demographics', models.ManyToManyField(to='api.demographic')),
                ('genres', models.ManyToManyField(to='api.genre')),
                ('themes', models.ManyToManyField(to='api.theme')),
            ],
        ),
    ]
