# Generated by Django 6.0 on 2025-12-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaitem',
            name='chapters',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mangaitem',
            name='volumes',
            field=models.IntegerField(null=True),
        ),
    ]
