# Generated by Django 6.0 on 2025-12-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mangaitem_chapters_alter_mangaitem_volumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangaitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
