# Generated by Django 6.0 on 2025-12-30 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mangaitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangaitem',
            name='isbn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
