# Generated by Django 6.0 on 2026-02-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mangaitem_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangaitem',
            name='cover',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
