# Generated by Django 6.0 on 2026-02-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mangaitem_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaitem',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='manga_covers/'),
        ),
    ]
